[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]



[project]
name = "spimpack"
version = "0.1.0"
description = "SPIM dataset packaging/publishing tool with pluggable backends"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Khan Lab"}]


[project.scripts]
spimpack = "spimpack.cli:main"
spimpack-ui = "spimpack.ui.launcher:main"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.pypi-dependencies]
spimpack = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }

[tool.pixi.workspace.dependencies]
tk = ">=8.6.13,<9"
pyyaml = ">=6.0.3,<7"
pybids = ">=0.22.0,<0.23"
streamlit = ">=1.58.0,<2"
pandas = ">=3.0.3,<4"
starlette = ">=0.47,<1.4"


[tool.pixi.package]
name = { workspace = true } # Inherit from the workspace
version = { workspace = true }

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "*" }

[tool.pixi.package.host-dependencies]
hatchling = "*"

[tool.pixi.dependencies]
tk = { workspace = true }
pyyaml = { workspace = true }
pybids = { workspace = true }
streamlit = { workspace = true }
pandas = { workspace = true }
starlette = { workspace = true }

[tool.pixi.package.run-dependencies]
tk = { workspace = true }
pyyaml = { workspace = true }
pybids = { workspace = true }
streamlit = { workspace = true }
pandas = { workspace = true }
starlette = { workspace = true }

