on:
  workflow_dispatch: # Enables the manual trigger button

jobs:

  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC token
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.0

      # Build and publish in one step -- no stored secrets needed!
      - run: pixi publish --target-channel https://prefix.dev/channels/@akhanf/khanlab
